south = ["space"]
east = ["left_ctrl"]
north = ["f"]
west = ["c", "mouse_side"]
up = ["up", "k", "2"]
down = ["down", "j", "4"]
left = ["left", "h", "1"]
right = ["right", "l", "3"]
forward = ["w"]
backward = ["s"]
starboard = ["d"]
port = ["a"]
l1 = ["mouse_right"]
r1 = ["mouse_left"]
l2 = ["q", "mouse_extra"]
r2 = ["x"]
l3 = ["left_alt"]
r3 = ["v"]
start = ["enter"]
select = ["tab"]
