[workspace]
resolver = "2"
members = ["crates/*", "ui/src-tauri"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Clemens Horn <me@clemenshorn.com>"]

[workspace.metadata.crane]
name = "joymouse"
