[toolchain]
channel = "1.87.0"
components = ["clippy", "rustfmt", "rust-analyzer", "rust-src", "llvm-tools"]
targets = ["x86_64-pc-windows-gnu", "x86_64-unknown-linux-gnu", "x86_64-unknown-linux-musl"]

[profile.release]
opt-level = 3
