[package]
name = "controller"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
settings = { path = "../settings" }
serde = { version = "1.0.219", features = ["derive"] }
