[package]
name = "controller"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
settings = { path = "../settings" }
key = { path = "../key" }

[target.'cfg(not(windows))'.dependencies]
epoll = "4.3.3"
evdev = "0.13.1"
