[package]
name = "controller"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
ctrlc = "3.4.7"
serde = { version = "1.0.219", features = ["derive"] }
settings = { path = "../settings" }
tauri = "2.8.4"
