[package]
name = "controller"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
epoll = "4.3.3"
evdev = "0.13.1"
config = { path = "../config" }
