[package]
name = "platform"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
settings = { path = "../settings" }
io = { path = "../io" }

[target.'cfg(not(windows))'.dependencies]
epoll = "4.3.3"
evdev = "0.13.1"
