[package]
name = "io"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
controller = { path = "../controller" }

[target.'cfg(not(windows))'.dependencies]
evdev = "0.13.1"
